version: "3.4"

services:
  database:
    container_name: database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
      - redis

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A celery_worker.app worker
    env_file:
      - .env
    depends_on:
      - app

volumes:
  db_data:
